Added query fetches search for join existence when applying JPA ordering.
spring-projects/spring-data-jpa pull request #2434
Opened 2022-02-08 19:54 UTC by AntonMolganov

Closes #2253
See https://github.com/spring-projects/spring-data-build/issues/2253

2022-02-09 07:58 UTC, schauder commented
The "See" link 404s, should that go to #2253?

2022-02-09 08:34 UTC, AntonMolganov commented
> The "See" link 404s, should that go to #2253?

Fixed pull request message.
Was .../spring-data-build/... insteadof .../spring-data-jpa/...

2022-02-09 17:30 UTC, schauder requested changes
We would need an integration test to go with this. `UserRepositoryTests` would probably a good home for that.

2026-07-15 07:05 UTC, schauder commented
This is still missing tests, and should have been automatically closed a long time ago.

2026-07-15 07:05 UTC, closed without merging