Properly handle native queries with SpEL
spring-projects/spring-data-jpa pull request #3109
Opened 2023-08-11 17:24 UTC by gregturn

2023-08-14 07:04 UTC, mp911de requested changes
Generally, this PR isn't fitting to our existing code. `AbstractStringBasedJpaQuery` already creates a `ExpressionBasedStringQuery` that we IMO should render properly to avoid downstream issues.

Adding more context to a `DeclaredQuery` factory adds more dependencies that aren't within the actual scope of the query wrapper.

We should rather eagerly render the query so that downstream components work with the already resolved expressions.

2023-09-06 21:37 UTC, gregturn commented on spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/query/DeclaredQuery.java
> +	static DeclaredQuery of(@Nullable String query, Boolean nativeQuery, @Nullable JpaQueryMethod method) {
I have tweaked that method signature to instead pass in `JpaEntityMetadata`.

2023-09-06 21:47 UTC, gregturn commented
> Generally, this PR isn't fitting to our existing code. AbstractStringBasedJpaQuery already creates a ExpressionBasedStringQuery that we IMO should render properly to avoid downstream issues.

The problem is that our current flow of processing a query simply doesn't get that far before it tries to extract the `QueryEnhancer`, which causes JSqlParser to break on the SpEL expression.

<img width="1142" alt="Screenshot 2023-09-06 at 4 44 35 PM" src="https://github.com/spring-projects/spring-data-jpa/assets/311040/447a5202-f1b6-4f7e-8add-5100b75fe455">

I'm actually trying to get in front of the call to `QueryEnhancerFactory.forQuery("select * from #{#entityName}")` and slide in an `ExpressionBaseQueryParser`. So yes, it is a little hacky. Let me re-read the code a little closer, and maybe I can restructure things such that we do this overall process sooner, or at least delay finding the `QueryEnhancer` for a given query until AFTER we have established what type of query it is.

2023-09-07 00:55 UTC, gregturn commented
@mp911de I drafted an alternative solution over at https://github.com/spring-projects/spring-data-jpa/pull/3145 that is much less intrusive. What do you think?

2023-09-12 15:48 UTC, closed without merging